version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules:/lib/modules:ro
      - /sys/kernel/debug:/sys/kernel/debug:ro
      # - ./server_binary:/host/server:ro
    ports:
      - "8080:8080"
      - "2112:2112"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
